package com.merryapps.rxarch.model.abstraction;

/**
 * Any operation that generates data and/or intents to modify the state of the system is considered
 * as an event. The actor (called the event generator) generating the event can be UI, the device,
 * the network, etc.
 *
 * <p>
 *   An event encapsulates data generated by the event.
 * </p>
 *
 * //TODO citation needed
 *
 * @author Pravin Sonawane
 * @since 0.0.1
 */
public interface Event<T> {

  T getData();
}
